### ISSUE TITLE
Linker problems (arm64)

### ISSUE THREAD

**Issue by StasKalishenko** [apotocki/icu4c-iosx#10]
Hi! I'm getting a linker problems like 
"Undefined symbols:
Linker command failed with exit code 1 (use -v to see invocation)"

If to look deeper in logs, it's said that:
ld: warning: ignoring file '/Users/myuser/Projects/myapp/ios/icu4c-iosx/product/lib/libicutu.a[25](xmlparser.ao)': found architecture 'x86_64', required architecture 'arm64'
 
And such warnings are for a a lot of *.ao files. Do you know how to fix it? It sounds like ICU was built for everything, but not for arm64.

**Comment by apotocki** [comment]
Hi! If you don't want to use cocoapods you should link XCFrameworks instead of libraries in the lib folder. Each xcframework contains libraries for all platforms. Frameworks are in product/frameworks. The instructions about linking you can find e.g. here: https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project

**Comment by StasKalishenko** [comment]
It didn't help. After adding "pod 'icu4c-iosx'" in Podfile and running "pod install", it downloaded icu4c-iosx to Pods folder, but while building the app there is an error 'Library 'icudata' not found'.
Possibly, it's better to add frameworks manually.

**Comment by apotocki** [comment]
Have you removed direct linking with .a files you previously did? Or perhaps something is wrong with your Xcode project. This repository has a demo project with a pod file. Try to compile it. Have you the same linking problems with it?
